baseURL = 'https://quilted-tutorial.github.io/SPARC-guru'
languageCode = 'en-us'
title = 'SPARC FAIR Codeathon'
theme = 'ananke'

SectionPagesMenu = "main"

[params]
    site_logo = "logos/quilt_logo.png"

